#!/usr/bin/env bash

convert() {
pandoc --to=plain --citeproc --csl=jneuro.csl "${@/#/--bibliography=}" << EOF
---
nocite: |
  @*
---
EOF
}

embolden_myself() {
  sed 's/\(Holmes CD\)/\*\*\1\*\*/'
}

convert "$@" | embolden_myself
