#!/usr/bin/env bash

h1() { echo ; echo "# $@" ; echo ; }
h2() { echo ; echo "## $@" ; echo ; }

h1 Publications
./bib2md bibs/publications.bib

h1 Conferences

h2 Graduate
./bib2md bibs/grad.bib

h2 Undergraduate
./bib2md bibs/undergrad.bib

h2 Extracurricular
./bib2md bibs/extracurricular.bib
